export default {
  FETCH_KITTENS: 'KITTEN_FETCH_KITTENS',
  FETCH_KITTENS_SUCCESS: 'KITTEN_FETCH_KITTENS_SUCCESS',
  FETCH_KITTENS_ERROR: 'KITTEN_FETCH_KITTENS_ERROR',

  ADD_KITTEN: 'KITTEN_ADD_KITTEN',
  ADD_KITTEN_SUCCESS: 'KITTEN_ADD_KITTEN_SUCCESS',
  ADD_KITTEN_ERROR: 'KITTEN_ADD_KITTEN_ERROR'
};